### ISSUE TITLE
Ventura UAMDM machines install no profile

### ISSUE THREAD

**Issue by K1jaff** [jamf/ReEnroller#10]
Testing this out on Ventura 13.1 and ABM enrollments are working fine but UAMDM devices are left with no profile as /usr/local/bin/jamf enroll -invitation xxxxxxx -noRecon -noPolicy -noManage is used to add the jamf client. Is that expected behaviour or are my settings wrong?

	<key>callEnrollment</key>
	<string>yes</string>
	<key>createConfSwitches</key>
	<string>always</string>
	<key>httpProtocol</key>
	<string>https</string>
	<key>jamfSchool</key>
	<integer>0</integer>
	<key>markAsMigrated</key>
	<false/>
	<key>maxRetries</key>
	<string>3</string>
	<key>mgmtAccount</key>
	<string>jamf</string>
	<key>migratedAttribute</key>
	<string></string>
	<key>newEnrollment</key>
	<integer>0</integer>
	<key>newJSSHostname</key>
	<string>jamf.com</string>
	<key>newJSSPort</key>
	<string>443</string>
	<key>postInstallPolicyId</key>
	<string></string>
	<key>removeAllProfiles</key>
	<string>false</string>
	<key>removeMDM</key>
	<true/>
	<key>removeMdmWhen</key>
	<string>Before</string>
	<key>removeReEnroller</key>
	<string>yes</string>
	<key>skipHealthCheck</key>
	<string>no</string>
	<key>skipMdmCheck</key>
	<string>no</string>
	<key>theNewInvite</key>
	<string>xxxxxxxxxxxx</string>

**Comment by BIG-RAT** [comment]
Is expected.  Devices not enrolled an ABM would require some other method to get an MDM profile on the device.
