### ISSUE TITLE
Clarification question ...

### ISSUE THREAD

**Issue by captam3rica** [jamf/ReEnroller#4]
I see in the code that the `profiles renew -type enrollment` command is used during the process. Is Automated Device Enrollment through ABM with this command attempted first and then fall back to a manual "UIE" enrollment if the Mac is not currently in ABM?

If the above is the case, does the important note in the README still apply for ABM machines enrolled with the `profiles` command via ABM, or even then, will the end-user be required to manually approve the enrollment profile within System Preferences?

**Comment by BIG-RAT** [comment]
The `profiles renew...` command is used just to kick off the the notification nag regarding device enrollment for devices in ABM.  It's up to the user to click and go through the process of automated device enrollment, overriding the MDM profile installed (pre Big Sur) as part of the re-enrollment process.  For Big Sur the user must initiate the profile installation whether the device is in ABM or not.

Hope that helps.

**Comment by captam3rica** [comment]
Nope that's perfect! Thanks!
