### ISSUE TITLE
Reenrolling in the old server in Catalina

### ISSUE THREAD

**Issue by damacguy** [jamf/ReEnroller#8]
More testing to do, but I'm not sure what the problem could be.

Configured with the new Jamf Server and correct user/pass. Package and process worked fine on a Mojave machine, but on my clean test Catalina machine it reenrolls in the original server! WTH?

Watched the MDM and config profiles get removed, and then new ones get installed. The MDM profile requires user approval as expected, but it's for the old MDM server.

Looked at the settings.plist from the pkg and 	<key>newJSSHostname</key> is listed correctly.

Checked that there's not something in DNS pointing the machine to the old server with the new server's URL for some reason (not setup for that anyway).

I'll retry with the same package back on Mojave... can't think why it's pulling the old server though. The reenrollment account doesn't even exist on the old server.

**Comment by BIG-RAT** [comment]
Make sure the machine is not assigned to a prestage associated with the original server.

On Nov 2, 2022, at 3:09 PM, Chris Waldrip ***@***.***> wrote:

﻿

More testing to do, but I'm not sure what the problem could be.

Configured with the new Jamf Server and correct user/pass. Package and process worked fine on a Mojave machine, but on my clean test Catalina machine it reenrolls in the original server! WTH?

Watched the MDM and config profiles get removed, and then new ones get installed. The MDM profile requires user approval as expected, but it's for the old MDM server.

Looked at the settings.plist from the pkg and newJSSHostname is listed correctly.

Checked that there's not something in DNS pointing the machine to the old server with the new server's URL for some reason (not setup for that anyway).

I'll retry with the same package back on Mojave... can't think why it's pulling the old server though.

**Comment by damacguy** [comment]
Stupid user issue... since this was my test machine there was already a device in the target Jamf system. I deleted that existing previous test and the new test worked... sort of. Now I'm getting a Device Signature Error, so I'm off to look at the other open issue about that issue (although this isn't on Monterey, but Mojave actually - sigh). Step by step...
